### ISSUE TITLE
RAW support

### ISSUE THREAD

**Issue by lentyay** [irungentoo/Xiaomi_Yi_4k_Camera#14]
Hi. Any chance You'll add RAW support to latest firmwares? Some instructions i found here but didn't try it.
https://dashcamtalk.com/forum/threads/basic-raw-support-on-firmware-1-4-0.28418/

**Comment by siriux** [comment]
I did't try the new firmware yet, but instructions should be the same, as it's not writing to specific memory addresses.

**Comment by MidoriYakumo** [comment]
t app test enable_rawcap 1

works for Yi4k in 1.4.23, only for photo mode, RAW file is under root dir

**Comment by zgmladen** [comment]
"t app test enable_rawcap 1"

It does not work on firmware 1.5.1

**Comment by MidoriYakumo** [comment]
1.6.1 official DNG comes!
