### ISSUE TITLE
Send and Receive API Commands/Data over bluetooth

### ISSUE THREAD

**Issue by somacoder** [irungentoo/Xiaomi_Yi_4k_Camera#31]
Is there any way to interface with the 4K using API commands over Bluetooth instead of wifi? i.e. - connect and communicate over an advertised bluetooth MAC address as opposed to the 192.168.42.1 wifi ip address. As you mentioned, both interface at the Linux level of the camera so you would think it would be possible.

**Comment by irungentoo** [comment]
I have not looked at the protocol of the bluetooth remote yet so other than switching from picture mode to video mode and taking pictures/video I'm not sure what's possible to do with it.

**Comment by MidoriYakumo** [comment]
it is possible you need mock as a BLE HIDdevice to send some keycode
