### ISSUE TITLE
Automatically Power On Yi 4K

### ISSUE THREAD

**Issue by somacoder** [irungentoo/Xiaomi_Yi_4k_Camera#34]
Hi irungentoo. Really love the work you've done here.

Do you know of a way to have the Yi 4K turn on automatically when power is connected? I notice the  light comes on shortly. I have power connected directly to the board and a relay the switches it on. It would be nice if it automatically turned on once receiving power.

Thanks!

**Comment by irungentoo** [comment]
I don't think it's possible to change the way it turns on with a software mod.
