### ISSUE TITLE
Bitrate mode for timelapse

### ISSUE THREAD

**Issue by sousek** [irungentoo/Xiaomi_Yi_4k_Camera#52]
Hi, i have question if it is possible set higher bitrate for timelapse video mode?
Which address will be for 4K/30 and 2.7K/30. 
Thanks for reply.

**Comment by irungentoo** [comment]
Try changing the bitrate of the regular 4k@30 and 2.7k@30 modes.

**Comment by sousek** [comment]
It works, thank you.

**Comment by MidoriYakumo** [comment]
I suggest you to capture still image for timelapse video, JPEG sequence has much more better quality than YI h264 presets.,
If available, use RAW, it provides best quality of the camera, however you need CinemaDNG workflow like Davinci Resolve to process them.
