### ISSUE TITLE
4K+ - Increase 4K HD (4000x3008) frame rate to 60 FPS... or

### ISSUE THREAD

**Issue by somacoder** [irungentoo/Xiaomi_Yi_4k_Camera#66]
Hi irungentoo,
     Is there a way to increase the frame rate of the 4K HD mode (4000x30008) to 60 FPS or perhaps it would be easier to do an ultra increased resolution mod on the native 4K (3840x2160) 60 mode to be 4000x3008?

Thanks!

**Comment by x4080** [comment]
Hi @somacoder, what is the use case for that resolution (4000x3000), is it for moving around in post ?

genuine question, I'm curious

**Comment by somacoder** [comment]
That resolution allows more field of view in the vertical direction, making full use of the sensor and lens at 4:3. the 4K 60 constrains that vertical FOV to 16:9. I am using it to film subjects situated close to the camera who may splay their arms out (I situate the camera vertically) so I need those extra degrees to capture that. A lot more data is lost at 16:9.

**Comment by x4080** [comment]
Thanks for the explanation

**Comment by alex-rptrv** [comment]
Can the camera capture video in 4:3 and 60 FPS ?

With best regards 

Magnus Jansson 
CTO 
Raptor Vision, LLC 
+46767777751

**Comment by somacoder** [comment]
Yes. I think 1920x1440 is the next highest the 4K+ can capture at 60, but the 4K model can also do that and costs half as much, so it doesn’t make much sense. Missed opportunity for Yi to capitalize on achieving somewhere better in the middle with the improved processor.

**Comment by MidoriYakumo** [comment]
No, the sensor has max read out of 34 fps at 4000x300, you can refer the specs from Sony.
